JD-365: Added skip for adding transaction for AFT
rbkmoney/midgard pull request #132
Opened 2021-06-08 12:56 UTC by avcherkasov

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +        private Transactions transactions;
ExcludeTransactions лучше описывает суть происходящего

2021-06-08 13:32 UTC, D-Baykov commented on pom.xml
> +        <version>1.2.3</version>
1.2.4 или выше

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +    }
Будет лучше как отдельный сервис по проверке операции

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +            Integer changeId, long sequenceId
форматирование поехало (лучше когда каждый параметр на отдельной строке)

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +            Integer changeId, long sequenceId
форматирование поехало (лучше когда каждый параметр на отдельной строке)

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/handler/invoicing/PaymentStatusChangedEventHandler.java
> +
лишние строки

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/handler/invoicing/PaymentStatusChangedEventHandler.java
> +        }
это тоже должно переехать в отдельный сервис, а тут ты только должен проверить скипнуть операцию или нет

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +    }
по-моему что-то похожее в адаптере должно быть. Посмотри плс

2021-06-08 13:32 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/KafkaConfig.java
> -        factory.getContainerProperties().setAckOnError(false);
посмотри необходимость указания данного параметра в errorHandler

2021-06-08 13:34 UTC, D-Baykov reviewed
Не увидел теста на реализованный функционал. (успех\не успех и т.п.)

2021-06-15 12:30 UTC, D-Baykov requested changes

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/KafkaConfig.java
> -        factory.getContainerProperties().setAckOnError(false);
Вопрос все еще открыт. Там что-то похожее в errorHandler нужно указать?

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +        private ExcludeTransactions excludeTransactions;
С названиями явно пролетели. Правильнее будет ExcludeOperationParams, так как от ExcludeTransactions ожидаешь список конкретных операций

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +public class CheckTransactionType {
Не самое лучшее название для сервиса. В названии как минимум должно это показываться + у него по-хорошему должен быть интерфейс. OperationCheckingService будет более к месту

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +    }
это можно в Utils вынести. В рамках мидгарда это как минимум в одном месте еще есть

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +            InvoicePayment invoicePayment,
можно тут не переносить на новую строку, чтобы было что-то типа public boolean isTypeTransactionToSkipped(InvoicePayment invoicePayment,

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +            int providerId
а вот тут int providerId) {

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +    public boolean isTypeTransactionToSkipped(
Тут лучше сделать так как по мне
public boolean isTypeTransactionToSkipped(ClearingAdapter clearingAdapter,

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +            long sequenceId
long sequenceId) {

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +            }
можно excludeTransactionType вынести до условия transactionInfo != null, а в самом условий проверить 2 параметра и по результату кинуть false, либо произвести сверку

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +        private String[] types;
Можно сделать сразу как List и потом не нужна будет обертка Array.stream

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +                .isPresent();
можно сделать что-то типа 
```
extractClearingAdapter(providerId)
    .filter(adapter -> isTypeTransactionToSkipped(
                        adapter, invoicePayment, invoiceId, changeId, sequenceId))
    .isPresent();
```

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +    public boolean isTypeTransactionToSkipped(
Название тоже можно суть скорректировать. Например, isOperationForSkip

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +            return transactionTypes.isPresent();
можно тоже сразу в return сделать

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/CheckTransactionType.java
> +    public boolean isTypeTransactionToSkipped(
почему тут 2 метода поясни плс?

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +    public static Transaction transformRefundTransaction(
почему не оставить так как было?

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +    public static ClearingEventTransactionInfo transformClearingRefund(
непонятное форматирование. Все же умещалось в 120 символов

2021-06-15 12:30 UTC, D-Baykov commented on src/test/java/com/rbkmoney/midgard/service/check/CheckTransactionTypeTest.java
> +    public void isTypeTransactionToSkippedTrueTest() {
с нэймингом мне кажется что-то не то) Ну и в целом нужно будет подогнать под изменения, которые описал выше

2021-06-15 12:30 UTC, D-Baykov commented on src/test/java/com/rbkmoney/midgard/service/check/CheckTransactionTypeTest.java
> +    }
подобные вещи хотелось бы спрятать в TestUtils, чтобы видеть только суть теста без конструкторов

2021-06-15 12:30 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    public static class ExcludeTransactions {
судя по тому, как ты это внес в application yaml (и я согласен с этим вариантом) этот класс должен быть частью адаптера, а не самого сервиса

2021-06-15 14:22 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/handler/invoicing/PaymentStatusChangedEventHandler.java
> +                adapters, payment, invoiceId, changeId, event.getEventId(), payment.getRoute().getProvider().getId())) {
> payment.getRoute().getProvider().getId()

ты там уже payment передаешь и можешь это вывести в сервисе

2021-06-15 14:22 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/OperationCheckingService.java
> +    public boolean isOperationForSkip(List<ClearingAdapter> adapters,
список адаптеров ты можешь сюда заинжектить же и не передавать его в параметрах метода

2021-06-15 14:22 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                                                              long sequenceId) {
прокидывать сюда столько параметров ради лога не оч. Лучше сделать отдельный exception, его перехватывать и там логировать как надо. Тут InvoicePayment invoicePayment и его логи будет достаточно как по мне

2021-06-15 14:22 UTC, D-Baykov commented on src/test/java/com/rbkmoney/midgard/utils/OperationCheckingServiceUtils.java
> +    }
Вот это лучше вернуть обратно, чтобы было понятно какой сервис ты тестишь

2021-06-15 14:28 UTC, D-Baykov commented on src/test/java/com/rbkmoney/midgard/utils/OperationCheckingServiceUtils.java
> +        OperationCheckingService operationCheckingService = new OperationCheckingService();
да и в целом в рамках теста, ты это по идее должен 1 раз создать, а потом проверить работу метода на различных данных

2021-06-15 14:34 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/service/check/OperationCheckingService.java
> +    public boolean isOperationForSkip(List<ClearingAdapter> adapters,
Он используется в PaymentStatusChangedEventHandler, там уже заинжекчен этот список, поэтому и пробрасываю

2021-06-15 14:37 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/OperationCheckingService.java
> +    public boolean isOperationForSkip(List<ClearingAdapter> adapters,
Ну заинжекть сюда и убери параметр из метода (он тут по большому счету не нужен). Убери invoiceId, changeId и sequenceId перереработав логирование исключения и сигнатура метода будет вполне себе.

2021-06-15 14:41 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                                                              long sequenceId) {
Да, только ради логов прокидывал, чтобы оставить совместимость в другом методе, где эти параметры ради логов прокидывались

2021-06-15 14:49 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                                                              long sequenceId) {
https://github.com/rbkmoney/midgard/blob/55dba81355b38416325763c4783ce25a949f3968/src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java#L200

2021-06-15 14:55 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                                                              long sequenceId) {
Это значит, что надо переработать код и там и тут, чтобы и ошибку кидал, но и логировалось все корректно в конечном итоге

2021-06-16 10:39 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/OperationCheckingService.java
> +                .anyMatch(value -> extra.containsValue(value.toLowerCase()));
думаю тут можно сделать что-то типа transactionInfo.getExtra().containsValue(value.toLowerCase()
либо проверить extra на null

2021-06-16 10:39 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                .orElseThrow(() -> new NotFoundException("Session for transaction with not found!"));
добавь инфу о invoicePayment

2021-06-16 10:39 UTC, D-Baykov commented on src/test/java/com/rbkmoney/midgard/service/check/OperationCheckingServiceTest.java
> +class OperationCheckingServiceTest {
из теста сложно понять где ты тестишь сам сервис. По-хорошему в assert'ах ты должен тестить вызов isOperationForSkip с определенными тестовыми invoicePayment.

2021-06-16 10:46 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    @Component
1. По аналогии с SchedulerProperties, чтобы не отходить от твоего стиля написания: https://github.com/rbkmoney/midgard/blob/master/src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java#L43

2. Там уже указываются настройки адаптера, добавил к ним лишь 1 параметр:
https://github.com/rbkmoney/midgard/blob/master/src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java#L29

3. Адаптеры достают настройки из AdapterProperties, которые указаны в ClearingServiceProperties
https://github.com/rbkmoney/midgard/blob/master/src/main/java/com/rbkmoney/midgard/config/AdaptersConfig.java#L20

2021-06-16 10:46 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    public static class ExcludeOperationParams {
см. комментарий выше

2021-06-16 11:04 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    public static class ExcludeOperationParams {
Да, осознал. 
Окс, пусть будет тут, но аннотация Component тут скорей всего лишняя

2021-06-16 11:04 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    @Component
окс, тогда в этом плане вопрос снимается, но п.1 еще актуален

2021-06-16 11:23 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    @Component
Убрав нотацию @Component, получаем ошибку: Not registered via @EnableConfigurationProperties, marked as Spring component, or scanned via @ConfigurationPropertiesScan

2021-06-16 11:29 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    public static class ExcludeOperationParams {
https://github.com/rbkmoney/midgard/pull/132#discussion_r652595362

2021-06-16 11:45 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/config/props/ClearingServiceProperties.java
> +    @Component
Странно. Обычно и без этого работало. Ну ок

2021-06-16 11:56 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/service/check/OperationCheckingService.java
> +        }
можно объединить

2021-06-16 11:59 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                        String.format("Session for transaction with not found! Payment id %s",
я имел в виду всю структуру залогировать, чтобы можно было из нее понять что пришло. Тупо payment id ни о чем не скажет

2021-06-16 12:06 UTC, avcherkasov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                        String.format("Session for transaction with not found! Payment id %s",
она же огромная =) Как скажешь

2021-06-16 12:23 UTC, D-Baykov commented on src/main/java/com/rbkmoney/midgard/utils/MappingUtils.java
> +                        String.format("Session for transaction with not found! Payment id %s",
Кстати, про огромность - чекни плс настройки кафки. Там по идее должен быть таймаут на ошибки, но если нет, то выстави плс

2021-06-16 13:00 UTC, D-Baykov approved these changes

2021-06-16 13:05 UTC, merged